version: "3.7"
services:
  app:
    container_name: "feat-service"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: "mongodb://db:27017"
      DATABASE: "foot"
    depends_on:
      - db
    links:
      - db
  db:
    image: mongo:latest
    restart: always
    container_name: "db"
    ports:
      - 27017:27017
